### ISSUE TITLE
「↗」でメッセージに飛んでほしい

### ISSUE THREAD

**Issue by ras0q** [hackathon-21-spring-02/front-end#46]
現状ファイルに飛んでるけどメッセージの方がうれしい
https://github.com/hackathon-21-spring-02/back-end/issues/52 が終わればすぐできそう

**Comment by ras0q** [comment]
終わったのでできます

**Comment by SSlime-s** [comment]
@Ras96 swagger.yaml に messageID ついてない

**Comment by ras0q** [comment]
https://github.com/hackathon-21-spring-02/back-end/pull/57
